// <auto-generated />
namespace Namaa.BioMetrics.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeLogDataInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeLogDataInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201903141116174_changeLogDataInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
